// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUAIytl1PxSkEpTUJ0OoMn98EHrTgk4QQ',
    appId: '1:833490458542:web:0c76c3718243a4277d5a3f',
    messagingSenderId: '833490458542',
    projectId: 'gestionbibliotheque-a8b1e',
    authDomain: 'gestionbibliotheque-a8b1e.firebaseapp.com',
    storageBucket: 'gestionbibliotheque-a8b1e.firebasestorage.app',
    measurementId: 'G-D1ELQEZ9P9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyP-obx1FLiz6r1rDuzIcQG6QNp_ZBsho',
    appId: '1:833490458542:android:4431383ca9d855f97d5a3f',
    messagingSenderId: '833490458542',
    projectId: 'gestionbibliotheque-a8b1e',
    storageBucket: 'gestionbibliotheque-a8b1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV2O__CVrP8eGR-hLXVjiNFG9QjQTJv8c',
    appId: '1:833490458542:ios:5dd147793af986347d5a3f',
    messagingSenderId: '833490458542',
    projectId: 'gestionbibliotheque-a8b1e',
    storageBucket: 'gestionbibliotheque-a8b1e.firebasestorage.app',
    iosBundleId: 'com.example.gestionBibliotheque',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV2O__CVrP8eGR-hLXVjiNFG9QjQTJv8c',
    appId: '1:833490458542:ios:5dd147793af986347d5a3f',
    messagingSenderId: '833490458542',
    projectId: 'gestionbibliotheque-a8b1e',
    storageBucket: 'gestionbibliotheque-a8b1e.firebasestorage.app',
    iosBundleId: 'com.example.gestionBibliotheque',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUAIytl1PxSkEpTUJ0OoMn98EHrTgk4QQ',
    appId: '1:833490458542:web:be05be940ee400b07d5a3f',
    messagingSenderId: '833490458542',
    projectId: 'gestionbibliotheque-a8b1e',
    authDomain: 'gestionbibliotheque-a8b1e.firebaseapp.com',
    storageBucket: 'gestionbibliotheque-a8b1e.firebasestorage.app',
    measurementId: 'G-KM6VE3RPZ8',
  );
}
