// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVGNFelB6K_L3No9WqR41iCkGLvoHk-3E',
    appId: '1:590834146972:web:ee46ff5de1caecd692d759',
    messagingSenderId: '590834146972',
    projectId: 'gestionbibliotheques',
    authDomain: 'gestionbibliotheques.firebaseapp.com',
    storageBucket: 'gestionbibliotheques.firebasestorage.app',
    measurementId: 'G-4SSPJD2EX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFqLCdSfA8ri6P-TqG7R8Z43fpkF1IWU4',
    appId: '1:590834146972:android:80b2cd6d2fd41bd192d759',
    messagingSenderId: '590834146972',
    projectId: 'gestionbibliotheques',
    storageBucket: 'gestionbibliotheques.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqW_jaOR4q9lRbIyLHRrAmoTkGwSxblfY',
    appId: '1:590834146972:ios:11fa52f9132c67c592d759',
    messagingSenderId: '590834146972',
    projectId: 'gestionbibliotheques',
    storageBucket: 'gestionbibliotheques.firebasestorage.app',
    iosBundleId: 'com.example.gestionBibliotheque',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqW_jaOR4q9lRbIyLHRrAmoTkGwSxblfY',
    appId: '1:590834146972:ios:11fa52f9132c67c592d759',
    messagingSenderId: '590834146972',
    projectId: 'gestionbibliotheques',
    storageBucket: 'gestionbibliotheques.firebasestorage.app',
    iosBundleId: 'com.example.gestionBibliotheque',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVGNFelB6K_L3No9WqR41iCkGLvoHk-3E',
    appId: '1:590834146972:web:759ad455d17493cb92d759',
    messagingSenderId: '590834146972',
    projectId: 'gestionbibliotheques',
    authDomain: 'gestionbibliotheques.firebaseapp.com',
    storageBucket: 'gestionbibliotheques.firebasestorage.app',
    measurementId: 'G-9PE2EJWDQC',
  );
}
